name: The personal website of Kris Janssen
description: "Science, Engineering and other things"
meta_description: "Science, Engineering and other things"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://krisjanssen.github.io'
google_analytics: 'UA-70086899-1'
disqus: true
disqus_shortname: 'KrisPFJanssen'

# Details for the RSS feed generator
url:            'http://krisjanssen.github.io'
author:         'Kris Janssen'
authorTwitter:  'KrisJanssen'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

gems: [jekyll-paginate]
